
services:
  backend_django:
    container_name: backend_django
    build: 
      context: ./django_backend
      dockerfile: Dockerfile
    env_file: 
      - .env.sample
    ports: 
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    networks:
      - backend_network
    depends_on:
      database_postgres:
        condition: service_healthy
    volumes:
      - ./django_backend:/django_backend
    environment:
      - POSTGRES_HOST=database_postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - DJANGO_PORT=${DJANGO_PORT}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "python3 manage.py check api"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s



  database_postgres:
    container_name: database_postgres
    env_file: 
      - .env.sample
    image: postgres:15
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=database_postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_NAME}"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge


